name: My first Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: install node modules
        run: npm
      - name: Build the project
        - run: npm build
      - name: Setup finish
        - run: echo "Hooray"
